spring.application.name=logistics
logging.level.root=INFO

# H2 데이터베이스 설정
spring.datasource.url=jdbc:h2:mem:logisticsdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console 사용 (웹에서 DB 확인용)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. JPA / Hibernate 설정 (Dialect 명시)
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 단일 파일 최대 업로드 용량 제한
spring.servlet.multipart.max-file-size=500MB
# 한 번의 Request 전체 최대 용량 제한
spring.servlet.multipart.max-request-size=500MB

# 비동기/스트리밍 요청 타임아웃을 무제한(-1)으로 설정
spring.mvc.async.request-timeout=-1

ai.server.url=${PYTHON_AI_URL:http://localhost:8000}
#ai.server.url=http://localhost:8000